name: build
on: [push]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: bash configure
      - name: Run make
        run: make images
      - name: verify JDK
        run: ./build/*/images/jdk/bin/java -version
      - name: run tests
        run: make run-test-tier1
